# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Enhanced Google Search MCP Server
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/dist ./dist

# Install only production dependencies
RUN npm ci --production --ignore-scripts

# Expose no port since stdio transport
CMD ["node", "dist/server.js"]
